//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationSystem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankDetail
    {
        public int BankDetailsID { get; set; }
        public int StudentID { get; set; }
        public string BankName { get; set; }
        public string CardHolder { get; set; }
        public string CardNumber { get; set; }
        public string Cvc { get; set; }
        public System.DateTime ExpiryDate { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
