//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationSystem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Registration()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int RegistrationID { get; set; }
        public string PaymentPlanID { get; set; }
        public int StudentID { get; set; }
        public Nullable<int> AdminID { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public decimal AmountDue { get; set; }
        public decimal AmountPayed { get; set; }
        public bool IsApproved { get; set; }
        public string ReasonNotApproved { get; set; }
        public Nullable<System.DateTime> NextPayment { get; set; }
        public byte PaymentCycle { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual PaymentPlan PaymentPlan { get; set; }
        public virtual Student Student { get; set; }
    }
}
