//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationSystem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subject()
        {
            this.RegisteredSubjects = new HashSet<RegisteredSubject>();
        }
    
        public string SubjectCode { get; set; }
        public int TeacherID { get; set; }
        public string SubjectName { get; set; }
        public string SubjectDescription { get; set; }
        public decimal SubjectPrice { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegisteredSubject> RegisteredSubjects { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
