//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationSystem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportingDocument
    {
        public int SupportingDocumentID { get; set; }
        public int StudentID { get; set; }
        public byte[] File { get; set; }
        public string FileName { get; set; }
        public bool IsVerified { get; set; }
        public string ContentType { get; set; }
        public string FileType { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
