<%@ Page Title="Student Portal" Language="C#" MasterPageFile="~/Student/Details/DetailsMaster.master" AutoEventWireup="true" CodeBehind="Payments.aspx.cs" Inherits="RegistrationSystem.Student.Details.Payments" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ExtraStyles" runat="server">
    <style>
        .pay-active {
            border: 2px solid #fd1d1d;
            border: 2px solid rgba(253, 29, 29, 1);
            color: #fd1d1d;
            color: rgba(253, 29, 29, 1);
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <h1 class="h6 m-0 text-muted">Payment Records</h1>
    <asp:PlaceHolder runat="server" ID="PaymentTable" Visible="false">
        <div runat="server" id="PaymentRecord">
            <div class="card text-center shadow-0 w-100">
                <div class="card-header px-1 px-sm-3 d-flex justify-content-between align-items-baseline">
                    <h1 class="h6">Payment Records</h1>
                    <button runat="server" id="SaveBtn" type="button" class="btn btn-primary rounded-pill no-text-wrap">
                        print now
                    </button>
                </div>
                <div class="card-body px-1 px-sm-3">
                    <div class="text-start row justify-content-between">
                        <div class="col-sm-6">
                            <h1 class="h6">Full Name(s)</h1>
                            <p class="fw-bold text-muted" runat="server">
                                <%= CurrentUser.FirstName %>
                                <%= CurrentUser.LastName %>
                            </p>
                        </div>
                        <div class="col-sm-6 text-end">
                            <h1 class="h6">Email Address</h1>
                            <p class="fw-bold text-muted" runat="server"><%= CurrentUser.Email %></p>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <asp:GridView ID="PaymentsGrid" runat="server" CssClass="table table-striped table-bordered text-center w-100"
                                      Caption="Payment Records"
                                      AutoGenerateColumns="false"
                                      AutoGenerateDeleteButton="false"
                                      AutoGenerateEditButton="false"
                                      AutoGenerateSelectButton="false"
                                      HeaderStyle-CssClass="main-gradient text-light">
                            <Columns>
                                <asp:BoundField DataField="PaymentId" HeaderStyle-CssClass="no-text-wrap" ItemStyle-CssClass="text-center"
                                                HeaderText="#" InsertVisible="False"
                                                ReadOnly="True"/>
                                <asp:BoundField DataField="Amount" HeaderStyle-CssClass="no-text-wrap" ItemStyle-CssClass="text-center"
                                                HeaderText="Amount Payed" SortExpression="Amount" ReadOnly="true" DataFormatString="{0:C}"/>
                                <asp:BoundField DataField="PaymentDescription" HeaderStyle-CssClass="no-text-wrap" ItemStyle-CssClass="text-center"
                                                HeaderText="Reference" ReadOnly="true"/>
                                <asp:BoundField DataField="PaymentDate" HeaderStyle-CssClass="no-text-wrap" ItemStyle-CssClass="text-center"
                                                HeaderText="Payment Date" SortExpression="PaymentDate" ReadOnly="true"/>
                                <%--<asp:BoundField DataField="Success"
                            HeaderText="Payment Success" SortExpression="Success" ReadOnly="true" />--%>
                                <asp:TemplateField HeaderText="Payment Status" HeaderStyle-CssClass="no-text-wrap">
                                    <ItemTemplate>
                                        <div class="text-center">
                                            <span class='<%# ((bool) Eval("Success")) ? "text-success" : "text-danger" %> fs-6 fw-bold'>
                                                <%# ((bool) Eval("Success")) ? "success" : "failed" %>
                                            </span>
                                        </div>
                                    </ItemTemplate>
                                </asp:TemplateField>
                            </Columns>
                        </asp:GridView>
                    </div>
                </div>
                <div class="card-footer">
                    <h1 runat="server" class="h6 text-muted"><%= DateTime.Now.ToString("F") %></h1>
                </div>
            </div>
        </div>
        <div class="text-end mb-5"></div>
    </asp:PlaceHolder>
    <asp:PlaceHolder runat="server" ID="NoPayments" Visible="false">
        <div class="card text-center shadow-0">
            <div class="card-body">
                <img height="250" src="~/Content/Static/empty.svg" runat="server"/>
                <h1 class="h3">No Payment Records</h1>
                <p class="lead">Seems like you have not made any payments yet!</p>
            </div>
        </div>
    </asp:PlaceHolder>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ClientContent" runat="server">
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="ExtraScript" runat="server">
    <script>
        (() => {
            const saveBtn = document.getElementById("<%= SaveBtn.ClientID %>");
            const docx = document.getElementById("<%= PaymentsGrid.ClientID %>");
            // ReSharper disable once InconsistentNaming
            const { jsPDF } = window.jspdf;
            var opt = {
                filename: 'payments.pdf',
                image: { type: 'jpeg', quality: 1 },
                html2canvas: {
                    scale: 1,
                    dpi: 600,
                    imageTimeout: 0,
                    letterRendering: true,
                },
                jsPDF: { unit: 'mm', format: 'A4', orientation: 'landscape', putOnlyUsedFonts: true },
                pagebreak: { mode: ['avoid-all', 'css'] }
            };
            saveBtn.addEventListener("click",
                () => {
                    html2canvas(docx).then(function(canvas) {
                        var wid;
                        var hgt;
                        const img = canvas.toDataURL("image/png", wid = canvas.width, hgt = canvas.height); //image data of canvas
                        const hratio = hgt / wid;

                        // ReSharper disable once InconsistentNaming
                        const doc = new jsPDF('p', 'mm', 'a4');
                        doc.setProperties({
                            title: 'Payment Record',
                            subject: 'User Payment Record',
                            author: 'Mpilo Ntombela',
                            keywords: 'ISTN3, MajorProject, System',
                            creator: 'Mpilo Ntombela'
                        });

                        const width = doc.internal.pageSize.width;
                        var height = doc.internal.pageSize.height;
                        height = width * hratio;
                        const x = (width / 2).toFixed();
                        doc.setTextColor(40);
                        doc.text(80, 10, "Payment Records");
                        doc.setFontSize(12);
                        doc.setTextColor('#808080');
                        doc.addImage(img, 'PNG', width * .025, 60, width * .95, height * .95);
                        doc.text(10, 30, 'Student Name: <%= CurrentUser.FirstName %> <%= CurrentUser.LastName %>');
                        doc.text(10, 40, 'Student Email: <%= CurrentUser.Email %>');
                        doc.text(10, 50, `Printing Date : ${new Date().toLocaleString("en-ZA")}`);
                        doc.autoPrint({ variant: 'non-conform' });
                        try {
                            doc.output('dataurlnewwindow',
                                {
                                    filename: `Payments-${new Date().toLocaleDateString("en-ZA")}.pdf`
                                });

                        } catch (e) {
                            doc.save(`Payments-${new Date().toLocaleDateString("en-ZA")}.pdf`);
                        }
                    });
                });
        })()
    </script>
</asp:Content>